"""23-stage ClawRank pipeline state machine.

Adapted from AutoResearchClaw's 23-stage academic pipeline.
Replaces paper-writing stages with SEO/GEO content generation stages
while preserving the state machine, gate logic, rollback rules, and
checkpoint/resume infrastructure.

Pipeline overview:
  Phase A: Niche Discovery      (1-2)   -- Understand the niche, entities, audiences
  Phase B: Keyword Intelligence  (3-6)   -- Discover, cluster, prioritize keywords
  Phase C: Competitive Intel     (7-8)   -- Analyze competitors, find gaps, plan content
  Phase D: Deep Research         (9-11)  -- Research briefs, data collection, evidence building
  Phase E: Content Generation    (12-13) -- Multi-agent drafting and refinement
  Phase F: SEO/GEO Optimization  (14-15) -- Schema, meta, internal links, GEO signals
  Phase G: Quality Assurance     (16-19) -- Quality gate, editorial review, link verification
  Phase H: Publishing            (20-23) -- Framework adapters, sitemap, deploy, archive
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, IntEnum
from typing import Iterable


class Stage(IntEnum):
    """23-stage SEO/GEO content pipeline."""

    # Phase A: Niche Discovery
    NICHE_INIT = 1           # Parse niche, detect framework, set goals
    NICHE_DECOMPOSE = 2      # Topic clusters, entities, audience segments

    # Phase B: Keyword Intelligence
    KEYWORD_STRATEGY = 3     # Search strategy, seed keywords, data sources
    KEYWORD_COLLECT = 4      # Scrape autocomplete, PAA, sitemaps, forums, academic
    KEYWORD_SCREEN = 5       # Cluster, dedupe, score, classify intent  [GATE]
    ENTITY_EXTRACT = 6       # Extract entities for comparison matrix

    # Phase C: Competitive Intelligence
    COMPETITOR_ANALYSIS = 7  # Crawl top rankings, extract patterns
    CONTENT_PLAN = 8         # Map clusters -> content types, prioritize, calendar

    # Phase D: Deep Research
    RESEARCH_BRIEF = 9       # Per-piece research brief                 [GATE]
    DATA_COLLECT = 10        # Mine data: gov, academic, APIs, pricing, jobs
    EVIDENCE_BUILD = 11      # Evidence cards, citations, unique data points

    # Phase E: Content Generation
    CONTENT_DRAFT = 12       # Multi-agent content generation
    CONTENT_REFINE = 13      # Iterative refinement on quality scores

    # Phase F: SEO/GEO Optimization
    SEO_OPTIMIZE = 14        # Schema markup, meta tags, internal links
    GEO_OPTIMIZE = 15        # Answer targets, structured claims, freshness

    # Phase G: Quality Assurance
    QUALITY_GATE = 16        # AI-slop detection, E-E-A-T, originality  [GATE]
    EDITORIAL_REVIEW = 17    # Multi-agent editorial review
    CONTENT_REVISION = 18    # Revise based on review feedback
    LINK_VERIFY = 19         # Verify external links and citations

    # Phase H: Publishing
    FRAMEWORK_ADAPT = 20     # Generate framework-specific output (MDX, WP, etc.)
    SITEMAP_GEN = 21         # XML sitemap, robots.txt, internal link graph
    PUBLISH = 22             # Deploy to target framework or output deliverables
    KNOWLEDGE_ARCHIVE = 23   # Update niche KB, extract lessons for self-learning


class StageStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    BLOCKED_APPROVAL = "blocked_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    PAUSED = "paused"
    RETRYING = "retrying"
    FAILED = "failed"
    DONE = "done"


class TransitionEvent(str, Enum):
    START = "start"
    SUCCEED = "succeed"
    APPROVE = "approve"
    REJECT = "reject"
    TIMEOUT = "timeout"
    FAIL = "fail"
    RETRY = "retry"
    RESUME = "resume"
    PAUSE = "pause"


# ---------------------------------------------------------------------------
# Content type classification
# ---------------------------------------------------------------------------

class ContentType(str, Enum):
    """Content archetypes generated by ClawRank."""
    COMPARISON = "comparison"           # "[A] vs [B]"
    BEST_FOR = "best_for"              # "Best [X] for [Y]"
    GLOSSARY = "glossary"              # "What is [term]?"
    STATISTICS = "statistics"          # "[Niche] statistics 2026"
    PILLAR = "pillar"                  # Ultimate guide / comprehensive resource
    HOW_TO = "how_to"                  # Step-by-step instructional
    LISTICLE = "listicle"              # "N [Topic] strategies that work"
    FAQ = "faq"                        # Aggregated questions
    RESOURCE = "resource"              # Calculator, tool, scorecard
    SEASONAL = "seasonal"              # Seasonal / time-bound content
    # Scotty-specific types
    SCENARIO = "scenario"              # AC framework scenario post
    DEEP_DIVE = "deep_dive"            # AC framework deep-dive
    CONTRARIAN = "contrarian"          # AC framework contrarian post
    GAP_FILL = "gap_fill"             # SEO gap-fill post


class SearchIntent(str, Enum):
    """Query intent classification."""
    INFORMATIONAL = "informational"
    COMMERCIAL = "commercial"
    TRANSACTIONAL = "transactional"
    NAVIGATIONAL = "navigational"


# ---------------------------------------------------------------------------
# Stage navigation
# ---------------------------------------------------------------------------

STAGE_SEQUENCE: tuple[Stage, ...] = tuple(Stage)

NEXT_STAGE: dict[Stage, Stage | None] = {
    stage: STAGE_SEQUENCE[idx + 1] if idx + 1 < len(STAGE_SEQUENCE) else None
    for idx, stage in enumerate(STAGE_SEQUENCE)
}

PREVIOUS_STAGE: dict[Stage, Stage | None] = {
    stage: STAGE_SEQUENCE[idx - 1] if idx > 0 else None
    for idx, stage in enumerate(STAGE_SEQUENCE)
}

# ---------------------------------------------------------------------------
# Gate stages -- require approval before proceeding
# ---------------------------------------------------------------------------

GATE_STAGES: frozenset[Stage] = frozenset(
    {
        Stage.KEYWORD_SCREEN,    # 5: Validate keyword clusters before proceeding
        Stage.RESEARCH_BRIEF,    # 9: Approve research plan before deep research
        Stage.QUALITY_GATE,      # 16: Final quality check before publishing
    }
)

GATE_ROLLBACK: dict[Stage, Stage] = {
    Stage.KEYWORD_SCREEN: Stage.KEYWORD_COLLECT,    # reject -> re-collect keywords
    Stage.RESEARCH_BRIEF: Stage.CONTENT_PLAN,       # reject -> re-plan content
    Stage.QUALITY_GATE: Stage.CONTENT_DRAFT,         # reject -> rewrite content
}

# ---------------------------------------------------------------------------
# Content decision rollback targets (from CONTENT_REFINE stage 13)
# ---------------------------------------------------------------------------

DECISION_ROLLBACK: dict[str, Stage] = {
    "pivot": Stage.CONTENT_PLAN,        # Scrap content plan, re-plan
    "refine": Stage.CONTENT_REFINE,     # Keep plan, re-refine content
}

MAX_DECISION_PIVOTS: int = 2

# ---------------------------------------------------------------------------
# Noncritical stages -- can be skipped on failure without aborting pipeline
# ---------------------------------------------------------------------------

NONCRITICAL_STAGES: frozenset[Stage] = frozenset(
    {
        Stage.LINK_VERIFY,        # 19: verification doesn't block publishing
        Stage.SITEMAP_GEN,        # 21: sitemap can be regenerated separately
        Stage.KNOWLEDGE_ARCHIVE,  # 23: archival doesn't block content output
    }
)

# ---------------------------------------------------------------------------
# Phase groupings (for UI and reporting)
# ---------------------------------------------------------------------------

PHASE_MAP: dict[str, tuple[Stage, ...]] = {
    "A: Niche Discovery": (Stage.NICHE_INIT, Stage.NICHE_DECOMPOSE),
    "B: Keyword Intelligence": (
        Stage.KEYWORD_STRATEGY,
        Stage.KEYWORD_COLLECT,
        Stage.KEYWORD_SCREEN,
        Stage.ENTITY_EXTRACT,
    ),
    "C: Competitive Intelligence": (Stage.COMPETITOR_ANALYSIS, Stage.CONTENT_PLAN),
    "D: Deep Research": (
        Stage.RESEARCH_BRIEF,
        Stage.DATA_COLLECT,
        Stage.EVIDENCE_BUILD,
    ),
    "E: Content Generation": (Stage.CONTENT_DRAFT, Stage.CONTENT_REFINE),
    "F: SEO/GEO Optimization": (Stage.SEO_OPTIMIZE, Stage.GEO_OPTIMIZE),
    "G: Quality Assurance": (
        Stage.QUALITY_GATE,
        Stage.EDITORIAL_REVIEW,
        Stage.CONTENT_REVISION,
        Stage.LINK_VERIFY,
    ),
    "H: Publishing": (
        Stage.FRAMEWORK_ADAPT,
        Stage.SITEMAP_GEN,
        Stage.PUBLISH,
        Stage.KNOWLEDGE_ARCHIVE,
    ),
}

# ---------------------------------------------------------------------------
# Content type -> intent mapping rules
# ---------------------------------------------------------------------------

INTENT_CONTENT_MAP: dict[SearchIntent, dict[str, ContentType]] = {
    SearchIntent.INFORMATIONAL: {
        "what is": ContentType.GLOSSARY,
        "how to": ContentType.HOW_TO,
        "statistics": ContentType.STATISTICS,
        "guide": ContentType.PILLAR,
    },
    SearchIntent.COMMERCIAL: {
        "vs": ContentType.COMPARISON,
        "best": ContentType.BEST_FOR,
        "review": ContentType.LISTICLE,
    },
    SearchIntent.TRANSACTIONAL: {
        "template": ContentType.RESOURCE,
        "tool": ContentType.RESOURCE,
        "calculator": ContentType.RESOURCE,
    },
}

# ---------------------------------------------------------------------------
# URL pattern templates per content type (Scotty's Green Lab -- all at /learn/{slug})
# ---------------------------------------------------------------------------

URL_PATTERNS: dict[ContentType, str] = {
    ContentType.COMPARISON: "/learn/{slug}",
    ContentType.BEST_FOR: "/learn/{slug}",
    ContentType.GLOSSARY: "/learn/{slug}",
    ContentType.STATISTICS: "/learn/{slug}",
    ContentType.PILLAR: "/learn/{slug}",
    ContentType.HOW_TO: "/learn/{slug}",
    ContentType.LISTICLE: "/learn/{slug}",
    ContentType.FAQ: "/learn/{slug}",
    ContentType.RESOURCE: "/learn/{slug}",
    ContentType.SEASONAL: "/learn/{slug}",
    ContentType.SCENARIO: "/learn/{slug}",
    ContentType.DEEP_DIVE: "/learn/{slug}",
    ContentType.CONTRARIAN: "/learn/{slug}",
    ContentType.GAP_FILL: "/learn/{slug}",
}

# ---------------------------------------------------------------------------
# Schema markup per content type
# ---------------------------------------------------------------------------

SCHEMA_MAP: dict[ContentType, tuple[str, ...]] = {
    ContentType.COMPARISON: ("Article", "BreadcrumbList", "Product", "Review"),
    ContentType.BEST_FOR: ("Article", "ItemList", "BreadcrumbList", "Product"),
    ContentType.GLOSSARY: ("Article", "DefinedTerm", "BreadcrumbList", "FAQPage"),
    ContentType.STATISTICS: ("Article", "Dataset", "BreadcrumbList"),
    ContentType.PILLAR: ("Article", "BreadcrumbList", "FAQPage", "WebPage"),
    ContentType.HOW_TO: ("HowTo", "Article", "BreadcrumbList", "FAQPage"),
    ContentType.LISTICLE: ("Article", "ItemList", "BreadcrumbList"),
    ContentType.FAQ: ("FAQPage", "BreadcrumbList", "WebPage"),
    ContentType.RESOURCE: ("WebApplication", "SoftwareApplication", "BreadcrumbList"),
    ContentType.SEASONAL: ("Article", "BreadcrumbList", "FAQPage"),
    ContentType.SCENARIO: ("Article", "BreadcrumbList", "FAQPage"),
    ContentType.DEEP_DIVE: ("Article", "BreadcrumbList", "FAQPage"),
    ContentType.CONTRARIAN: ("Article", "BreadcrumbList", "FAQPage"),
    ContentType.GAP_FILL: ("Article", "BreadcrumbList", "FAQPage"),
}


# ---------------------------------------------------------------------------
# Transition logic (identical to AutoResearchClaw)
# ---------------------------------------------------------------------------

TRANSITION_MAP: dict[StageStatus, frozenset[StageStatus]] = {
    StageStatus.PENDING: frozenset({StageStatus.RUNNING}),
    StageStatus.RUNNING: frozenset(
        {StageStatus.DONE, StageStatus.BLOCKED_APPROVAL, StageStatus.FAILED}
    ),
    StageStatus.BLOCKED_APPROVAL: frozenset(
        {StageStatus.APPROVED, StageStatus.REJECTED, StageStatus.PAUSED}
    ),
    StageStatus.APPROVED: frozenset({StageStatus.DONE}),
    StageStatus.REJECTED: frozenset({StageStatus.PENDING}),
    StageStatus.PAUSED: frozenset({StageStatus.RUNNING}),
    StageStatus.RETRYING: frozenset({StageStatus.RUNNING}),
    StageStatus.FAILED: frozenset({StageStatus.RETRYING, StageStatus.PAUSED}),
    StageStatus.DONE: frozenset(),
}


@dataclass(frozen=True)
class TransitionOutcome:
    stage: Stage
    status: StageStatus
    next_stage: Stage | None
    rollback_stage: Stage | None = None
    checkpoint_required: bool = False
    decision: str = "proceed"


def gate_required(
    stage: Stage,
    hitl_required_stages: Iterable[int] | None = None,
) -> bool:
    """Check whether a stage requires human-in-the-loop approval."""
    if stage not in GATE_STAGES:
        return False
    if hitl_required_stages is not None:
        return int(stage) in frozenset(hitl_required_stages)
    return True


def default_rollback_stage(stage: Stage) -> Stage:
    """Return the configured rollback target, or the previous stage."""
    return GATE_ROLLBACK.get(stage) or PREVIOUS_STAGE.get(stage) or stage


def advance(
    stage: Stage,
    status: StageStatus,
    event: TransitionEvent | str,
    *,
    hitl_required_stages: Iterable[int] | None = None,
    rollback_stage: Stage | None = None,
) -> TransitionOutcome:
    """Compute the next state given current stage, status, and event."""
    event = TransitionEvent(event)
    target_rollback = rollback_stage or default_rollback_stage(stage)

    if event is TransitionEvent.START and status in {
        StageStatus.PENDING, StageStatus.RETRYING, StageStatus.PAUSED,
    }:
        return TransitionOutcome(
            stage=stage, status=StageStatus.RUNNING, next_stage=stage
        )

    if event is TransitionEvent.SUCCEED and status is StageStatus.RUNNING:
        if gate_required(stage, hitl_required_stages):
            return TransitionOutcome(
                stage=stage, status=StageStatus.BLOCKED_APPROVAL,
                next_stage=stage, checkpoint_required=False, decision="block",
            )
        return TransitionOutcome(
            stage=stage, status=StageStatus.DONE,
            next_stage=NEXT_STAGE[stage], checkpoint_required=True,
        )

    if event is TransitionEvent.APPROVE and status is StageStatus.BLOCKED_APPROVAL:
        return TransitionOutcome(
            stage=stage, status=StageStatus.DONE,
            next_stage=NEXT_STAGE[stage], checkpoint_required=True,
        )

    if event is TransitionEvent.REJECT and status is StageStatus.BLOCKED_APPROVAL:
        return TransitionOutcome(
            stage=target_rollback, status=StageStatus.PENDING,
            next_stage=target_rollback, rollback_stage=target_rollback,
            checkpoint_required=True, decision="pivot",
        )

    if event is TransitionEvent.TIMEOUT and status is StageStatus.BLOCKED_APPROVAL:
        return TransitionOutcome(
            stage=stage, status=StageStatus.PAUSED,
            next_stage=stage, checkpoint_required=True, decision="block",
        )

    if event is TransitionEvent.FAIL and status is StageStatus.RUNNING:
        return TransitionOutcome(
            stage=stage, status=StageStatus.FAILED,
            next_stage=stage, checkpoint_required=True, decision="retry",
        )

    if event is TransitionEvent.RETRY and status is StageStatus.FAILED:
        return TransitionOutcome(
            stage=stage, status=StageStatus.RETRYING,
            next_stage=stage, decision="retry",
        )

    if event is TransitionEvent.RESUME and status is StageStatus.PAUSED:
        return TransitionOutcome(
            stage=stage, status=StageStatus.RUNNING, next_stage=stage
        )

    if event is TransitionEvent.PAUSE and status is StageStatus.FAILED:
        return TransitionOutcome(
            stage=stage, status=StageStatus.PAUSED,
            next_stage=stage, checkpoint_required=True, decision="block",
        )

    raise ValueError(
        f"Unsupported transition: {status.value} + {event.value} for stage {int(stage)}"
    )
